"""Add rol column to User

Revision ID: 0c157db4cfde
Revises: 
Create Date: 2025-11-15 11:09:53.608856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c157db4cfde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cards')
    op.drop_table('user_stories')
    op.drop_table('quick_tests')
    op.drop_table('user_settings')
    op.drop_table('user_preferences_questions')
    op.drop_table('review_logs')
    op.drop_table('quick_test_questions')
    op.drop_table('daily_fsrs_progress')
    op.drop_table('user_preferences')
    op.drop_table('daily_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('progress_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_kanji_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_kanji_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('today_kanji_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_progress_pkey'))
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_options', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['user_preferences_questions.id'], name=op.f('user_preferences_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_table('daily_fsrs_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('progress_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('kanji_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewed_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reviewed_cards', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.Column('todays_cards', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_fsrs_progress_pkey'))
    )
    op.create_table('quick_test_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kanji_char', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_meaning', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chosen_meaning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['quick_tests.id'], name=op.f('quick_test_questions_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quick_test_questions_pkey'))
    )
    op.create_table('review_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('review_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('write_time_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stroke_errors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('review_logs_card_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('review_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('review_logs_pkey'))
    )
    op.create_table('user_preferences_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('max_selection', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_questions_pkey'))
    )
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('daily_kanji_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('daily_srs_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_settings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_settings_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('quick_tests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wrong_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quick_tests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quick_tests_pkey'))
    )
    op.create_table('user_stories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kanji_char', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('story', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_stories_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_stories_pkey'))
    )
    op.create_table('cards',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kanji_char', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('due', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_review', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cards_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
